name: Scheduled Gmail Automate

on:
  schedule:
    # Runs at 10:00 am IST 
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Decode credentials.json
        run: echo "${{ secrets.CREDENTIALS_JSON_B64 }}" | base64 -d > credentials.json

      - name: Decode token.json
        run: echo "${{ secrets.TOKEN_JSON_B64 }}" | base64 -d > token.json

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GMAIL_TOKEN_PATH: token.json
          GMAIL_CREDENTIALS_PATH: credentials.json
        run: python main.py 
